[package]
name = "smelt"
version = "0.3.0"

[build]
c_standard = "c17"
warnings = "all"
src_dir = "src"
out_dir = "build"
link_flags = ["-lm"]
defines  = []
include_dirs = ["src", "vendor"]
extra_sources = ["vendor/xxhash.c", "vendor/tomlc17.c", "vendor/ya_getopt.c"]

[profile.debug]
flags = ["-g", "-O0"]

[profile.release]
flags = ["-O3", "-DNDEBUG"]

[dependencies]
testlib = { path = "./testlib" }
xxhash = "0.8.3"

[system-dependencies]
libgit2 = { pkg-config = "libgit2" }

