[package]
name = "smelt"
version = "0.4.0"

[build]
c_standard = "c17"
warnings = "all"
src_dir = "src"
out_dir = "build"
link_flags = ["-lm"]
defines = []
include_dirs = ["src"]
extra_sources = []

[profile.debug]
flags = ["-g", "-O0"]

[profile.release]
flags = ["-O3", "-DNDEBUG"]

[dependencies]
xxhash = "0.8.3"
tomlc17 = "1.0.0"
ya_getopt = "1.0.0"

[system-dependencies]
libgit2 = { pkg-config = "libgit2" }
